name: Check for New Feature Label

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-new-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR contains `[x] New feature`
        id: check_new_feature
        run: |
          if grep -q "\[x\] New feature" <<<"${{ github.event.pull_request.body }}"; then
            echo "new_feature=true" >> $GITHUB_ENV
          else
            echo "new_feature=false" >> $GITHUB_ENV

      - name: Add or remove `enhancement` label
        if: always() # This ensures that this step runs whether the previous step succeeds or fails.
        run: |
          NEW_FEATURE="${{ env.new_feature }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          if [ "$NEW_FEATURE" == "true" ]; then
            echo "Adding enhancement label..."
            gh pr edit "$PR_NUMBER" --add-label "enhancement"
          else
            echo "Removing enhancement label if it exists..."
            gh pr edit "$PR_NUMBER" --remove-label "enhancement"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
