name: Manage enhancement label on PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled, ready_for_review, review_requested, review_request_removed]

jobs:
  manage-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Analyze PR Body
        id: check-body
        run: |
          if echo "${{ github.event.pull_request.body }}" | grep -q '\- \[x\] New feature'; then
            echo "contains_feature=true" >> $GITHUB_ENV
          else
            echo "contains_feature=false" >> $GITHUB_ENV
          fi

      - name: Add enhancement label if feature is checked
        if: env.contains_feature == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "enhancement"

      - name: Remove enhancement label if feature is unchecked
        if: env.contains_feature == 'false'
        run: |
          curl -s -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/enhancement
