name: Label Enhancement

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  label-enhancement:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR body and manage labels
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prBody = context.payload.pull_request.body || "";

            // Fetch the current labels on the PR
            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const labels = currentLabels.map(label => label.name);
            const hasEnhancementLabel = labels.includes("enhancement");
            const newFeatureChecked = prBody.includes("- [x] New feature");

            if (newFeatureChecked && !hasEnhancementLabel) {
              // Add the "enhancement" label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ["enhancement"],
              });
            } else if (!newFeatureChecked && hasEnhancementLabel) {
              // Remove the "enhancement" label
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: "enhancement",
              });
            }
