name: Label Enhancement

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  label-enhancement:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR body and manage labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const prBody = context.payload.pull_request.body || "";

            console.log("PR Body:", prBody);

            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const labels = currentLabels.map(label => label.name);
            const hasEnhancementLabel = labels.includes("enhancement");

            // Normalize the PR body for matching
            const prBodyNormalized = prBody.toLowerCase().replace(/\s+/g, ' ');
            const newFeatureChecked = prBodyNormalized.includes('- [x] new feature');

            console.log("Has 'enhancement' label:", hasEnhancementLabel);
            console.log("Is 'New feature' checked:", newFeatureChecked);

            if (newFeatureChecked && !hasEnhancementLabel) {
              // Add the "enhancement" label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ["enhancement"],
              });
              console.log('Added "enhancement" label.');
            } else if (!newFeatureChecked && hasEnhancementLabel) {
              // Remove the "enhancement" label
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: "enhancement",
              });
              console.log('Removed "enhancement" label.');
            } else {
              console.log('No action needed.');
            }
