name: Manage labels based on PR body

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled, ready_for_review, review_requested, review_request_removed]

jobs:
  manage-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Analyze PR Body and manage labels
        run: |
          body="${{ github.event.pull_request.body }}"

          # Initialize the labels to be added and removed
          labels_to_add=()
          labels_to_remove=()

          # Check for enhancement
          if echo "$body" | grep -q '\- \[x\] New feature'; then
            labels_to_add+=("enhancement")
          else
            labels_to_remove+=("enhancement")
          fi

          # Check for bug-related labels (Bug fix, Hotfix, Security patch)
          if echo "$body" | grep -q '\- \[x\] Bug fix\|\- \[x\] Hotfix\|\- \[x\] Security patch'; then
            labels_to_add+=("bug")
          else
            labels_to_remove+=("bug")
          fi

          # Check for documentation update
          if echo "$body" | grep -q '\- \[x\] Documentation update'; then
            labels_to_add+=("documentation")
          else
            labels_to_remove+=("documentation")
          fi

          # Export the labels to add and remove as environment variables
          echo "LABELS_TO_ADD=${labels_to_add[*]}" >> $GITHUB_ENV
          echo "LABELS_TO_REMOVE=${labels_to_remove[*]}" >> $GITHUB_ENV

      - name: Add labels if necessary
        if: env.LABELS_TO_ADD != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS_TO_ADD }}

      - name: Remove labels if necessary
        run: |
          for label in ${{ env.LABELS_TO_REMOVE }}; do
            curl -s -X DELETE \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/$label
          done
