name: Manage labels based on PR body

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled, ready_for_review, review_requested, review_request_removed]

jobs:
  manage-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Analyze PR Body and manage labels
        run: |
          body="${{ github.event.pull_request.body }}"

          # Define label rules: each pair is [label_name, search_patterns (separated by \|)]
          declare -A label_patterns=(
            ["enhancement"]="- \[x\] New feature"
            ["bug"]="- \[x\] Bug fix\|- \[x\] Hotfix\|- \[x\] Security patch"
            ["documentation"]="- \[x\] Documentation update"
          )

          labels_to_add=()
          labels_to_remove=()

          for label in "${!label_patterns[@]}"; do
            if echo "$body" | grep -Eq "${label_patterns[$label]}"; then
              # Add label if any of the patterns are found
              labels_to_add+=("\"$label\"")
            else
              # Remove label if none of the patterns match
              labels_to_remove+=("\"$label\"")
            fi
          done

          # Add labels if any
          if [ ${#labels_to_add[@]} -gt 0 ]; then
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"labels\": [$(IFS=,; echo "${labels_to_add[*]}")]}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels
          fi

          # Remove labels if any
          for label in "${labels_to_remove[@]}"; do
            curl -s -X DELETE \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/$(echo $label | tr -d '"')
          done
